### ISSUE TITLE
Strange Card Tests

### ISSUE THREAD

**Issue by AxelAhlborn** [Speccery/StrangeCart-Doc#1]
Hi Eric, sorry for the "Issue". Is it possible to get a StrangeCart V2 rev B for tests ?

Greetings Axel

**Comment by Speccery** [comment]
Hi Axel,
Sorry for the super slow reply. If you don't mind getting in touch with me via the AtariAge forums or by email, we can talk about it.

**Comment by Speccery** [comment]
this is the link to AtariAge: 
https://forums.atariage.com/topic/306889-strangecart/page/18/#comments

**Comment by AxelAhlborn** [comment]
Hello Eric, since I can't make SMD-based circuits myself, I would like to
ask if I can purchase one from you. Even if it may have beta status.

Greetings, Axel


Erik Piehl ***@***.***> schrieb am Mi. 22. Nov. 2023 um 19:34:

**Comment by Speccery** [comment]
Hi Axel,Sure, I have a couple which are ready to go. They need firmware update and a quick test. Please email me at speccery (at) gmail (dot) com.

**Comment by AxelAhlborn** [comment]
Hi Eric, thank you very much ! Merry christmas and a happy new year. Greetings Axel
